---
title: "Figure 5"
output:
  html_document:
    toc: false
    includes:
      in_header: ../include/in_header.html
      before_body: ../include/before_body.html
      after_body: ../include/after_body.html
runtime: shiny_prerendered
---
<!-- # (c)  Juozas GordeviÄius -->

```{r, include=FALSE}
source("../code/common.R", chdir=TRUE)
require("ggrepel")
require("cowplot")

theme_publication <- function(font = 7) {
  theme(
    text = element_text(family = "Helvetica", size = font, color = "black"),
    plot.title = element_text(size = font, color = "black"),

    panel.background = element_rect(fill = "transparent", colour = NA),
    panel.border = element_blank(),
    plot.background = element_rect(fill = "transparent", colour = NA),

    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),

    axis.line = element_line(color = "black"),
    axis.text = element_text(size = font, color = "black"), 
    axis.ticks = element_line(size = 0.3, color = "black"),
    axis.title = element_text(size = font, color = "black"),

    # strip.background = element_rect(color = "white", fill = "white"),
    strip.text.x = element_text(size = font, color = "black"),
    strip.text.y = element_text(size = font, color = "black"),

    legend.background = element_rect(
      fill = alpha("white", 0),
      color = alpha("white", 0)
    ),
    legend.key = element_rect(color = NA, fill = NA),
    legend.key.size = unit(0.2, "cm"),    
    legend.text = element_text(size = font)
  )
}

pathways_human <- readRDS("../Discover_Pathways/humanPathways.RDS")

```


```{r}
# Load mice DSS fits
dss <- fread(Sys.glob("../Mice_DSS_Padlock/www/m6_*.csv"))

# Load CP fits
cp <- fread(Sys.glob("../Mice_CecalPatch_Padlock/www/m6_*.csv"))

# Load APX fits
apx <- fread(Sys.glob("../Appendix_PDvsControls_Padlock/www/m6_*.csv"))
```

```{r}

# dt <- dss[, list(
#     WT = `C.GTwt_DSS - GTwt_Water`, 
#     P.WT = `P.GTwt_DSS - GTwt_Water`, 
#     A30P = `C.GTtg_DSS - GTtg_Water`,
#   	P.A30P = `P.GTtg_DSS - GTtg_Water`)]

# dt[, PosEffect := FALSE]
# dt[, PosEffect := sign(WT) == sign(A30P) & abs(WT) < abs(A30P)]
# dt[, Significant :=p.adjust(P.WT, "fdr") < 0.05 | p.adjust(P.A30P, "fdr") < 0.05]
# myt <- dt[, table(PosEffect=PosEffect, Significant=Significant)]
# fisher.test(myt)
# dt <- rbind(
# 		data.table(Type=" NS", Risk=myt[2,1]/sum(myt[,1])),
# 		data.table(Type="Significant\ncytosines", Risk=myt[2,2]/sum(myt[,2])))
# dt[, Facette := "A30P > WT"]
# dt[, Odds := Risk / (1-Risk)]

# f <- fisher.test(myt) %>% broom::tidy()
# f$estimate <- format(f$estimate, digits=3)
# f$p.value <- 
# 	format(f$p.value, digits=3, scientific=TRUE) %>%
# 	gsub("e", "~x~10^", .)

# label = list(glue("'OR = '~{f$estimate}"), 
#              glue("'p = '~{f$p.value}"))

# pD <-
# 	ggplot(dt, aes(Type, Odds, color=Type, fill=Type)) + 
# 	geom_bar(stat="identity", width=0.7) + 
# 	geom_text(x = 0.5, 
# 	          y = 0.8 - c(0.02, 0.1), 
# 	          hjust=0,
# 	          color = "black",
# 	          label=label, 
# 	          parse=TRUE,
# 	          size = 2.2) + 
# 	# facet_wrap(~Facette) + 
# 	scale_fill_manual("", values=c("white", "grey30")) + 
# 	scale_color_manual("", values=c("grey30", "grey30")) + 
# 	guides(fill = FALSE, color = FALSE) + 
# 	ylim(0, 0.8) + 
# 	ggtitle("Increased DSS effect\nin A30P") +
# 	theme_publication() + 
# 	theme(axis.title.x = element_blank())

# # pD

```


```{r}
# Correlation of enrichments in CecalPatch and DSS

dt <- fread("../Results_Mice/ORs_CecalPatch_DSS.csv")
dt[, Star := gtools::stars.pval(p.value)]
dt <- dt[1:4]
dt[, Contrast := gsub("GT", "", Contrast)]
dt[, Contrast := gsub("wt", "WT", Contrast)]
dt[, Contrast := gsub("tg", "A30P", Contrast)]
dt[, Contrast := factor(Contrast, levels = Contrast)]
pB <- 
  ggplot(dt, aes(Contrast, estimate)) + 
  geom_bar(stat = "identity", color = "black", fill="white", size = 0.25) + 
  geom_text(aes(label = Star), vjust = -1, size = 2.2) + 
  ylab("Concordance") +
  theme_publication() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
# Correlation of enrichments in appendix vs Mice

dt <- fread("../Results_Mice/ORs_Appendix_Mice.csv")
dt[, Star := gtools::stars.pval(p.value)]
dt[, Contrast := gsub("GT", "", Contrast)]
dt[, Contrast := gsub("wt", "WT", Contrast)]
dt[, Contrast := gsub("tg", "A30P", Contrast)]
dt[5, Contrast := sprintf('rAAV \u03B1-syn')]
dt[, Contrast := factor(Contrast, levels = Contrast)]

pC <- 
  ggplot(dt, aes(Contrast, estimate)) + 
  geom_bar(stat = "identity", position=position_dodge(width=0.8), 
           color = "black", fill="white",
           size = 0.25, width=0.8) + 
  geom_text(aes(label = Star), 
            vjust = -0.3, hjust=0.5, size=3.3, #size = 2.2,
            color = "black",
          	position=position_dodge(width=0.8)) + 
  ylab("Concordance") +
  scale_y_continuous(limits=c(-0.02, 0.13)) + 
  scale_fill_manual(values = c("white", "grey")) + 
  theme_publication() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
# Venn diagrams
dt <- fread("../Results_Mice/Direction_Genes_Apendix_Mouse.csv")
```


```{r}
# Hyper
dtHyper <- 
  dt %>%
    .[, list(
            Appendix = Appendix == "Hyper-",
            `a-syn` = `rAAV a-syn` == "Hyper-" | `A30P_Water - WT_Water` == "Hyper-",
            `DSS` = `A30P_DSS - A30P_Water` == "Hyper-" | `WT_DSS - WT_Water` == "Hyper-"
        ), 
        HGNC_hg19]
resHyper <- 
  foreach( d = 0:1, .combine = rbind ) %:%
  foreach( s = 0:1, .combine = rbind ) %:%
  foreach( a = 0:1, .combine = rbind ) %:%
  foreach( i = 1:length(pathways_human), .combine = rbind) %do% {
    tryCatch({
      dtHyper[, table(HGNC_hg19 %in% pathways_human[[i]]$genes, Appendix == a & `a-syn` == s & DSS == d)] %>% 
      fisher.test %>%
      broom::tidy() %>% 
      mutate(Pathway = pathways_human[[i]]$name) %>%
      mutate(
        Apx = a, 
        `a-syn` = s, 
        DSS = d) %>%
      setDT
    }, error = function(e) {
      return(NULL)
    })
  }
resHyper[p.value < 0.05 & estimate > 1, list(estimate, p.value, Pathway, Apx, `a-syn`, DSS)]

# Now plot the venn diagram
df.venn <- data.frame(x = c(0, 0.866, -0.866), 
                      y = c(1, -0.5, -0.5), 
                      x.labels = c(-2, 1.2, -1.2), 
                      y.labels = c(2, -2.2, -2.2),
                      labels = c(' DSS\n colitis', 'Synucleinopathy', 'Appendix'))
vdc <- 
  dtHyper %>% 
  select(-HGNC_hg19) %>% 
  vennCounts

class(vdc) <- 'matrix'
df.vdc <- as.data.frame(vdc)[-1,] %>%
  mutate(x = c(0, 1.2, 0.8, -1.2, -0.8, 0, 0),
         y = c(1.2, -0.6, 0.5, -0.6, 0.5, -1, 0))

pacman::p_load("ggforce")
pD <- 
  df.venn %>% 
  mutate(Tissue = "Hypermodified genes") %>%
  ggplot() +
    geom_circle(aes(x0 = x, y0 = y, r = 1.5, fill = labels), alpha = .3, size = 0.25, colour = 'grey') +
    coord_fixed() +
    facet_grid(. ~ Tissue) +
    theme(legend.position = 'bottom') +
    scale_fill_manual(values = c('#0080FF', '#FF00FF',  '#006400'), guide=FALSE) +
    scale_colour_manual(values = c('#0080FF', '#FF00FF',  '#006400'), guide = FALSE) +
    labs(fill = NULL) +
    annotate("text", x = df.vdc$x, y = df.vdc$y, label = df.vdc$Counts, size = 2.2) + 
    annotate('text', x = df.venn$x.labels, y = df.venn$y.labels, label = df.venn$labels, size = 2.2) + 
    theme_publication() +
    theme(
          axis.line=element_blank(),axis.text.x=element_blank(),
          axis.text.y=element_blank(),axis.ticks=element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank())
pD
```


```{r}
# Hypo
dtHypo <- 
  dt %>%
    .[, list(
            Appendix = Appendix == "Hypo-",
            `a-syn` = `rAAV a-syn` == "Hypo-" | `A30P_Water - WT_Water` == "Hypo-",
            `DSS` = `A30P_DSS - A30P_Water` == "Hypo-" | `WT_DSS - WT_Water` == "Hypo-"
        ), 
        HGNC_hg19]

resHypo <- 
  foreach( d = 0:1, .combine = rbind ) %:%
  foreach( s = 0:1, .combine = rbind ) %:%
  foreach( a = 0:1, .combine = rbind ) %:%
  foreach( i = 1:length(pathways_human), .combine = rbind) %do% {
    tryCatch({
      dtHypo[, table(HGNC_hg19 %in% pathways_human[[i]]$genes, Appendix == a & `a-syn` == s & DSS == d)] %>% 
      fisher.test %>%
      broom::tidy() %>% 
      mutate(Pathway = pathways_human[[i]]$name) %>%
      mutate(
        Apx = a, 
        `a-syn` = s, 
        DSS = d) %>%
      setDT
    }, error = function(e) {
      return(NULL)
    })
  }
resHypo[p.value < 0.05 & estimate > 1, list(estimate, p.value, Pathway, Apx, `a-syn`, DSS)]

# Now plot the venn diagram
df.venn <- data.frame(x = c(0, 0.866, -0.866), 
                      y = c(1, -0.5, -0.5), 
                      x.labels = c(-2, 1.2, -1.2), 
                      y.labels = c(2, -2.2, -2.2),
                      labels = c(' DSS\n colitis', 'Synucleinopathy', 'Appendix'))
vdc <- 
  dtHypo %>% 
  select(-HGNC_hg19) %>% 
  vennCounts

class(vdc) <- 'matrix'
df.vdc <- as.data.frame(vdc)[-1,] %>%
  mutate(x = c(0, 1.2, 0.8, -1.2, -0.8, 0, 0),
         y = c(1.2, -0.6, 0.5, -0.6, 0.5, -1, 0))

pacman::p_load("ggforce")
pE <- 
  df.venn %>% 
  mutate(Tissue = "Hypomodified genes") %>%
  ggplot() +
    geom_circle(aes(x0 = x, y0 = y, r = 1.5, fill = labels), alpha = .3, size = 0.25, colour = 'grey') +
    coord_fixed() +
    facet_grid(. ~ Tissue) +
    theme(legend.position = 'bottom') +
    scale_fill_manual(values = c('#0080FF', '#FF00FF',  '#006400'), guide=FALSE) +
    scale_colour_manual(values = c('#0080FF', '#FF00FF',  '#006400'), guide = FALSE) +
    labs(fill = NULL) +
    annotate("text", x = df.vdc$x, y = df.vdc$y, label = df.vdc$Counts, size = 2.2) + 
    annotate('text', x = df.venn$x.labels, y = df.venn$y.labels, label = df.venn$labels, size = 2.2) + 
    theme_publication() +
    theme(
          axis.line=element_blank(),axis.text.x=element_blank(),
          axis.text.y=element_blank(),axis.ticks=element_blank(),
          axis.title.x=element_blank(),
           axis.title.y=element_blank())

```

```{r, include=TRUE, fig.width=7.2, fig.height=7.2}
# quartz("", 7.2, 7.2)
# X11("", 7.2, 7.2)
suppressWarnings(
  ggdraw() + 
    draw_image("../Figure5/Fig5_mousediagram.png", 
      x = 0, y = 0.85, width = 1, height = 0.15) + 
    draw_plot(pB + ylim(0, 0.25) + 
      ggtitle(sprintf("rAAV-\u03B1-syn vs\nDSS study")) + 
      theme(plot.title = element_text(face = "plain")),
      x = 0.02, y = 0.5, width = 0.2, height = 0.35) +
    draw_plot(pC + 
      ggtitle("PD appendix vs\nmice studies") + 
      theme(plot.title = element_text(face = "plain"),
            legend.position=c(0.4,0.9)),
      x = 0.22, y = 0.5, width = 0.2, height = 0.35) +
    draw_plot(pD,
      x = 0.43, y = 0.55, width = 0.3, height = 0.3) + 
    draw_text("Lysosomes: OR = 1.9 p = 0.03", 
      x = 0.43, y = 0.55, size = 7, hjust = 0,
       vjust = 0.5) + 
    draw_line(
         x = c(0.58, 0.58),
         y = c(0.56, 0.61),
         color = "black", size = 0.25,
         arrow = arrow(type = "open", angle = 30, length = unit(0.1, "inches"))
       ) + 
    draw_plot(pE,
      x = 0.7, y = 0.55, width = 0.3, height = 0.3) + 
    draw_text("Autophagy: OR = 2.16 p = 0.013", 
      x = 0.75, y = 0.55, size = 7, hjust = 0,
       vjust = 0.5) + 
    draw_line(
         x = c(0.825, 0.85),
         y = c(0.56, 0.67),
         color = "black", size = 0.25,
         arrow = arrow(type = "open", angle = 30, length = unit(0.1, "inches"))
       ) + 
    draw_plot_label(
      label = letters[1:3],
      size = 10,
      x = c(0, 0,    0.43),
      y = c(1, 0.85, 0.85))
)
ggsave("../Figure5/figure5.png", width = 7.2, height = 7.2, dpi = 300, units = "in")
```


